name: My first workflow

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
    
  workflow_dispatch:

# logic of the workflow 
jobs: 
  MyFirstJob:
    runs-on: ubuntu-latest # runner
    steps:
      - run: echo "ğŸ‘‹ğŸ¾ Hello World!"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: List files in repository
        run: |
          echo "This repository ${{ github.repository }} contains the following files:"
          tree
