name: My first workflow

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
    
  workflow_dispatch:

# logic of the workflow 
jobs: 
  MyFirstJob:
    runs-on: ubuntu-latest # runner
    steps:
      - name: Step1
        id: job1-step1
        run: |
          echo "ðŸ‘‹ðŸ¾ Hello World!"
          echo "hi=ðŸ‘‹" >> "$GITHUB_OUTPUT"
          echo "hi=ðŸŽ‰" >> "$GITHUB_ENV"

      - name: Checkout
        id: Step2
        uses: actions/checkout@v6.0.2

      - name: List files in repository
        id: list-files
        run: |
          echo "This repository ${{ github.repository }} contains the following files:"
          tree
          echo "We said: ${{ steps.job1-step1.outputs.hi }}"

      - name: Summary
        run: echo "### First Job Complete! ðŸ‘‹" >> $GITHUB_STEP_SUMMARY

  MySecondJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: |
          echo "Job: ${{ github.job }}"
          echo "Job1 said: ${{ env.hi }}"
      - name: Summary
        run: echo "### Second Job Complete! ðŸ‘‹" >> $GITHUB_STEP_SUMMARY

  MyThirdJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: "echo Job: ${{ github.job }}"

      - name: Summary
        run: echo "### Third Job Complete! ðŸ‘‹" >> $GITHUB_STEP_SUMMARY

  LastJob:
    runs-on: ubuntu-latest
    needs:
      - MySecondJob
      - MyThirdJob
    steps:
      - run: "echo Job: ${{ github.job }}"

      - name: Summary
        run: echo "### Last Job Complete! ðŸ‘‹" >> $GITHUB_STEP_SUMMARY
