name: My first workflow

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
    
  workflow_dispatch:

# logic of the workflow 
jobs: 
  MyFirstJob:
    runs-on: ubuntu-latest # runner
    steps:
      - run: echo "üëãüèæ Hello World!"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: List files in repository
        run: |
          echo "This repository ${{ github.repository }} contains the following files:"
          tree

  MySecondJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: "echo Job: ${{ github.job }}"

  MyThirdJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: "echo Job: ${{ github.job }}"

  LastJob:
    runs-on: ubuntu-latest
    needs:
      - MySecondJob
      - MyThirdJob
    steps:
      - run: "echo Job: ${{ github.job }}"

